## Jetty configuration
## No single request should take longer than 15s to return a response
##spring.datasource.master.url
##life_passport_write_jdbc_url=jdbc:mysql://112.124.49.40/life_passport?autoReconnect=true&characterEncoding=utf-8
##life_passport_write_jdbc_username=root
##life_passport_write_jdbc_password=LID989&dksdf00
##spring.datasource.druid.master
#spring:
#  datasource:
#    druid:
#      master:
#        url: jdbc:mysql://112.124.49.40/life_passport?autoReconnect=true&characterEncoding=utf-8
#        username: root
#        password: LID989&dksdf00
#        driverClassName: com.mysql.jdbc.Driver
#        dbType: mysql
#      slave:
#        url: jdbc:mysql://112.124.49.40/life_passport?autoReconnect=true&characterEncoding=utf-8
#        username: root
#        password: LID989&dksdf00
#        driverClassName: com.mysql.jdbc.Driver
#        dbType: mysql
#      slave2:
#        url: jdbc:mysql://112.124.49.40/life_passport?autoReconnect=true&characterEncoding=utf-8
#        username: root
#        password: LID989&dksdf00
#        driverClassName: com.mysql.jdbc.Driver
#        dbType: mysql
#
#
